export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INPUT_TEXT = 'INPUT_TEXT';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';